In [1]:
import numpy as np

In [5]:
# basic operation
A = np.array([4, 5, 6])
B = [1, 2, 3]
np.copyto(A, B)
A

array([1, 2, 3])

In [10]:
# ravel inplace/ flatten copy
# orders A=ANY, C=ROW, F=COLUMN, K=MEMORY
a = np.array([[1, 2], [3, 4]], order='C')  # Fortran-contiguous array
np.ravel(a, order='A')  # Output: [1, 3, 2, 4]

array([1, 2, 3, 4])

In [13]:
# ndarry.flat
a = np.arange(1, 7)
for i in a.flat:
    print(i)
a.flat = 3
a

1
2
3
4
5
6


array([3, 3, 3, 3, 3, 3])