In [1]:
import numpy as np

# numpy basics

In [5]:
# numpy array

a = np.array([1, 2, 3, 4, 5])
print(a)

# higher dimentinal array
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(a)
print(a.ndim, a.shape, a.size, a.dtype)

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]
2 (2, 4) 8 int64


In [6]:
# array inializar

print(
    np.zeros((3, 4)),
    np.ones((3, 2)),
    np.empty((2, 2)),
    np.arange(1, 10, 2),
    np.linspace(0, 1, 5),
    np.random.random((2, 3)),
    sep="\n\n"
)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0.00000000e+000 6.95302821e-310]
 [4.94065646e-324             nan]]

[1 3 5 7 9]

[0.   0.25 0.5  0.75 1.  ]

[[0.82302228 0.97178625 0.38537396]
 [0.57957674 0.93103725 0.30948627]]


In [10]:
# sorting
a = np.random.randint(1, 21, 10)
print(np.sort(a)) # sorted copy
a.sort() # inplace sort
a

[ 1  3  8  8  8  9 10 10 11 12]


array([ 1,  3,  8,  8,  8,  9, 10, 10, 11, 12], dtype=int32)

In [13]:
"""
    # concatenation
    arrays must be same size
"""

print(
    np.concatenate((
        np.arange(1, 5),
        np.arange(1, 13)
    ))
)

[ 1  2  3  4  1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
# reshape
print(
    np.arange(1, 26).reshape((5, 5))
)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [17]:
# transpose

a = np.arange(1, 21).reshape((4, 5))
print(
    "original Array: ",
    a,
    "transposed array: ",
    a.T, # also can be written as a.transpose()
    sep="\n\n"
)

original Array: 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

transposed array: 

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [19]:
# selection

a = np.array((
    [
        np.arange(i, i + 4)
        for i in range(1, 10, 4)       
    ]
))

print(
    a[a < 5], # elements less than 5
    a[a % 2 == 0], # divisible by 2
    a[(a > 2) & (a < 5)], # 2 < a <= 5
    sep="\n\n"
)

[1 2 3 4]

[ 2  4  6  8 10 12]

[3 4]


In [22]:
# stacking

a1 = np.arange(1, 5).reshape((2, 2))

a2 = np.arange(5, 9).reshape((2, 2))

print(
    "vstack:",
    np.vstack((a1, a2)),
    "hstack:",
    np.hstack((a2, a1)),
    sep="\n\n"
)

vstack:

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack:

[[5 6 1 2]
 [7 8 3 4]]


In [27]:
# split

x = np.arange(1, 25).reshape(2, 12)
print(
    np.vsplit(x, 2),
    np.hsplit(x, 6),
    sep="\n\n"
)


[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

[array([[ 1,  2],
       [13, 14]]), array([[ 3,  4],
       [15, 16]]), array([[ 5,  6],
       [17, 18]]), array([[ 7,  8],
       [19, 20]]), array([[ 9, 10],
       [21, 22]]), array([[11, 12],
       [23, 24]])]


In [29]:
# array operations

data = np.array((1, 2))
ones = np.ones((1, 2))
data + ones

array([[2., 3.]])

In [35]:
# broadcasting

data = np.array([1, 2])

print(data * 1.6)

# one row/column broadcasting

data = np.array(([1, 2], [3, 4], [5, 6]))
ones_col = np.ones((3, 1), dtype=np.int8)

data + ones_col

[1.6 3.2]


array([[2, 3],
       [4, 5],
       [6, 7]])

In [33]:
# aggregation operations

# 1D array
data = np.arange(1, 4)
print(
    data.max(),
    data.min(),
    data.sum(),
    data.mean(),
    data.prod(),
    data.std(),
    sep="\n\n"
)

# 2D array

data = np.arange(1, 7).reshape(3, 2)
print(
    data.min(axis=0),
    data.min(axis=1)
)

3

1

6

2.0

6

0.816496580927726
[1 2] [1 3 5]


In [63]:
# unique

a = np.random.randint(1, 5, 10)
unique_values, occurrence_count = np.unique(a, return_counts=True)

print(
    unique_values,
    occurrence_count,
    sep="\n"
)

[1 2 3 4]
[2 4 2 2]


In [78]:
# mathematical formulas

# MSE example
n = 5
predictions = np.array([2.5, 0.0, 2.1, 7.8, 5.5])
labels = np.array([3.0, -0.5, 2.0, 7.0, 5.0])

mse = (1 / n) * np.sum(np.square(predictions -  labels))
print(f"Mean Squared Error: {mse:.02}")

# some other functions
print(
    np.log(np.e), # e based log system
    np.sqrt(np.arange(0, 101, 10)),
    np.power(np.arange(1, 6), 2),
    np.sin(np.pi / 2),
    sep="\n\n"
)

# cross-entropy loss

m = 3
y_actual = np.concatenate(
    (np.ones(1), np.zeros(2))
)
y_pred = np.array((.7, .2, .1))

cross_entropy_loss = -1 / m * np.sum(y_actual * np.log(y_pred))
print(cross_entropy_loss)

# softmax function
x = np.array([1, 2, .1])

softmax = np.exp(x) / np.sum(np.exp(x))
print(softmax)

Mean Squared Error: 0.28
1.0

[ 0.          3.16227766  4.47213595  5.47722558  6.32455532  7.07106781
  7.74596669  8.36660027  8.94427191  9.48683298 10.        ]

[ 1  4  9 16 25]

1.0
0.11889164797957748
[0.24243297 0.65900114 0.09856589]
